### ISSUE TITLE
Harmonize BlockStore API

### ISSUE THREAD

**Issue by Bulat-Ziganshin** [status-im/nim-codex#123]
Current API:
- `getBlock: Future[?!Block]` - returns errmsg via Result. OK.
- `putBlock/delBlock: Future[bool]` - returns false if operation failed. FSStore uses `trace` to publish an actual error message
- `listBlocks: Future[void]` - the same use of `trace`
- `hasBlock: bool` - no Future, no Result

I think that we can live for a while without Future in hasBlock/contains, but what about the rest?

**Comment by Bulat-Ziganshin** [comment]
Current usage of these methods looks like:

---

Errmsg returned by getBlock is replaced by its own errmsg in:
- https://github.com/status-im/nim-codex/blob/6ad7a6bb96cc789d5038ab6a064be59ea6e1a9fb/codex/node.nim#L105

... printed in `trace` and returned in:
- https://github.com/status-im/nim-codex/blob/209343087c4acb00c5f9d9c448bff434146ccf10/codex/erasure/erasure.nim#L107

... converted into exception in:
- https://github.com/status-im/nim-codex/blob/28ebb16767cbf43dce2738fd4d9cfdf210b309dc/codex/streams/storestream.nim#L70

Failed block errmsgs are printed in `trace` and blocks are filtered out in:
- https://github.com/status-im/nim-codex/blob/209343087c4acb00c5f9d9c448bff434146ccf10/codex/erasure/erasure.nim#L182

... and failed blocks are silently filtered out in:
- https://github.com/status-im/nim-codex/blob/d4f3ebc867e2ade0dfffe479f442f69a5561e572/codex/blockexchange/engine/engine.nim#L371
- https://github.com/status-im/nim-codex/blob/6ad7a6bb96cc789d5038ab6a064be59ea6e1a9fb/codex/node.nim#L139

---

Bool result of putBlock is usually used to call `trace` and return failure:
- https://github.com/status-im/nim-codex/blob/6ad7a6bb96cc789d5038ab6a064be59ea6e1a9fb/codex/node.nim#L182
- https://github.com/status-im/nim-codex/blob/6ad7a6bb96cc789d5038ab6a064be59ea6e1a9fb/codex/node.nim#L203
- https://github.com/status-im/nim-codex/blob/209343087c4acb00c5f9d9c448bff434146ccf10/codex/erasure/erasure.nim#L142
- https://github.com/status-im/nim-codex/blob/209343087c4acb00c5f9d9c448bff434146ccf10/codex/erasure/erasure.nim#L245

... but here it's used to try operation and ignore failure:
- https://github.com/status-im/nim-codex/blob/d4f3ebc867e2ade0dfffe479f442f69a5561e572/codex/blockexchange/engine/engine.nim#L253

---

`delBlock` isn't used in current code at all :)

**Comment by Bulat-Ziganshin** [comment]
Proposed API (that closely resembles [nim-datastore](https://github.com/status-im/nim-datastore/blob/master/datastore/datastore.nim) ):
- `getBlock: Future[?! (?Block)]`
- `putBlock/delBlock/listBlocks: Future[?!void]`
- `hasBlock: Future[?!bool]`

Rationale:
- all real errors should be signaled via Return
- getBlock may fail to find a block with given id - return Block.none in this case in order to distinguish that from "hard failures", such as ruined DB. F.e. in BlockExc we can delete block in one task before another task get a chance to read it - it's not a failure at all
- putBlock can create new block or overwrite existing one - we don't care, thus `void`
- delBlock: if it can't delete a block - it's an error; if block already doesn't exist - we don't care (it may be deleted by other task)

**Comment by Bulat-Ziganshin** [comment]
While #130 implements above-described API, we agreed that getBlock return type should be changed to

> getBlock: Future[?!Block]

This means that attempt to read a block absent in Store should return an error. If we need to distinguish this from real errors, we should use hasBlock prior to getBlock.

**Comment by emizzle** [comment]
@Bulat-Ziganshin this was completed in #130, right, so this can be closed?

**Comment by Bulat-Ziganshin** [comment]
@emizzle Not yet, we agreed to make one more change in the API - see last comment

**Comment by emizzle** [comment]
@Bulat-Ziganshin I've created a new issue #182 for this change, and will close this issue in favour of that one.
