### ISSUE TITLE
Harden engineering

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-codex#139]
The goal of this epic is to find and fix bugs for the p2p mvp. Part of discovering bugs will rely on stress testing locally. Any issues discovered that require bug fixes should be included in this epic. We could potentially include testing tasks in here if needed.

**Comment by dryajov** [comment]
Does this epic/issue make any sense, it seems like we already have #146?

**Comment by Bulat-Ziganshin** [comment]
> Does this epic/issue make any sense, it seems like we already have #146?

I think that the only real subtask described in the first message is #140.

May be we also have some ideas for testing which I overheard during the meeting. "Fix bugs" isn't a task.

So, I propose to close this task as irrelevant one, unless we need it as umbrella task for some task tracking system.

**Comment by emizzle** [comment]
> May be we also have some ideas for testing which I overheard during the meeting. "Fix bugs" isn't a task.

A lot of this was created as part of our discussions in Bologna. We discussed that we need to harden engineering which includes finding and fixing bugs. From an epic perspective it makes sense, but yes I agree that from an issue perspective, it doesn't make much sense. But I don't want to close the epic, so I'll edit the description instead.

What would be nice to do is include any bugs found as subtasks inside of this epic, and then we can assign those issues individually and concretely.

**Comment by dryajov** [comment]
> 

Do we really need an epic to track individual bugs? I'm not opposed, but it's unusual to do this AFAIK.

**Comment by emizzle** [comment]
It’s definitely not conventional, but it’s nice to see on the Gantt chart, which is why it was created in the first place. We can remove the epic and keep individual bugs if we want, but in my opinion, it shouldn’t really matter that much, because it’s mostly visual. Engineers can find their tasks easily using the Board view. As an alternative, we could rename this to “Find and fix bugs”, or we could break this epic up in to other epics that have dates we want to display on the Gantt chart.

**Comment by Bulat-Ziganshin** [comment]
If we want to have smth in Gantt diagram, it definitely should have name better than "Harden engineering" or "Fix all bugs". I guess we want "Fix engineering showstoppers for V1 aka P2P MVP". Issues that we want to fix in this timescale are included in the [Milestone](https://github.com/status-im/nim-codex/milestone/1).

We can fix only bugs we know (and just now we have exactly one), and finding bugs is the goal of testing that is decribed in other issues.

I think we may keep this issue to discuss things because turning them into issues. Similarly, I created #165 epic for BlockStore-related part of engineering work.

**Comment by emizzle** [comment]
> I guess we want "Fix engineering showstoppers for V1 aka P2P MVP"

Sure, we can change the name to that. I also agree this epic is very much unconventional. For now I've unassigned you and @michaelsbradleyjr from this epic, as it doesn't make sense to have you assigned to it and it won't appear on your board. We can group bugs as they arise from testing into other epics, as you mentioned.
