### ISSUE TITLE
Integrate datastore in to Codex

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-codex#141]
Once SQLite is fully integrated in to nim-datastore.

GanttStart: 2022-07-15
GanttDue: 2022-07-20

**Comment by Bulat-Ziganshin** [comment]
Is it the same as #138 ?

**Comment by emizzle** [comment]
Yes, good point, closing.

**Comment by Bulat-Ziganshin** [comment]
let's delete this issue entirely!
