### ISSUE TITLE
Setup monitoring (metrics) in the client

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-codex#153]
1. Add metrics to the client, support grafana
- [ ] Collect bytes transferred
- [ ] Collect bytes stored
- [ ] Collect speed of upload/download
- [ ] ... TBD ...

**Comment by emizzle** [comment]
As per meeting on 28/7/22, @dryajov to look at taking a first stab at this.

**Comment by Bulat-Ziganshin** [comment]
It would be great to measure time required for BlockStore read/write calls
