### ISSUE TITLE
Update getBlock return type

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-codex#182]
While #130 implements above-described API, we agreed that getBlock return type should be changed to

> getBlock: Future[?!Block]

This means that attempt to read a block absent in Store should return an error. If we need to distinguish this from real errors, we should use hasBlock prior to getBlock.

**Comment by emizzle** [comment]
TBD whether it happens in both client and nim-datastore. Discussion needed.

**Comment by michaelsbradleyjr** [comment]
I suggest we start by making the change here in nim-codex, possibly later changing the return type in nim-datastore.

**Comment by Bulat-Ziganshin** [comment]
> I suggest we start by making the change here in nim-codex, possibly later changing the return type in nim-datastore.

yes, I prefer that too. Too much changes in nim-datastore, and there is a possibility that we will still need a function that distinguishes between failure and not-found
