### ISSUE TITLE
Replace protobuf serialization with minprotobuf

### ISSUE THREAD

**Issue by dryajov** [status-im/nim-codex#264]
Protobuf serialization has a number of issues that make it unsuitable for production use for the foreseeable feature, these shortcomings where fine while prototyping, but are an issue for production oriented development - for example it's not possible to use it with the latest version of libp2p due to dependencies and such.  

We already use minprotobuf in codex to serialize the manifest, we should also rewrite the https://github.com/status-im/nim-codex/blob/main/codex/blockexchange/protobuf/message.proto with minprotobuf. 

We could also rewrite https://github.com/status-im/nim-codex/blob/main/codex/storageproofs/por/serialization/por.proto, but this is going to be replaced with the new snark based approach which would not require serializing authenticators, so at least for now it's not a priority.

**Comment by Bulat-Ziganshin** [comment]
Example is https://github.com/status-im/nim-libp2p/blob/unstable/libp2p/protocols/pubsub/rpc/protobuf.nim
